---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.8

suites:
  - name: default12
    require_chef_omnibus: 12.21.3
    run_list:
      - recipe[telegraf-ng::default]
    attributes:
      telegraf:
        ignore_version: false

  - name: default13
    require_chef_omnibus: 13.2.20
    run_list:
      - recipe[telegraf-ng::default]
    attributes:
      telegraf:
        ignore_version: false
